site_name: Bio Sea Pearl
site_url: https://bibymaths.github.io/bio-sea-pearl/

repo_name: bibymaths/bio-sea-pearl
repo_url: https://github.com/bibymaths/bio-sea-pearl

theme:
  name: material
  language: en
  font:
    text: Ubuntu           # The font for standard paragraph text
    code: Fira Code        # The font for code blocks
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo # Change this to your brand color!
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Overview:
      - Architecture: architecture.md
      - API Reference: api.md
      - CLI Usage: cli.md
  - Modules:
      - Alignment: alignment.md
      - Markov: markov.md
      - SeqTools: seqtools.md
      - BWT & FM-index: bio_sea_pearl.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets

copyright: >
  Copyright &copy; 2026 <a href="https://bibymaths.github.io">Abhinav Mishra</a>.